# Generated by Django 4.1.9 on 2023-05-19 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('plural_name', models.CharField(blank=True, max_length=128, unique=True)),
                ('base_unit', models.CharField(blank=True, choices=[('G', 'g'), ('KG', 'kg'), ('ML', 'ml'), ('L', 'l'), ('OUNCE', 'ounce'), ('POUND', 'pound'), ('FLUID_OUNCE', 'fluid_ounce'), ('TSP', 'tsp'), ('TBSP', 'tbsp'), ('CUP', 'cup'), ('PINT', 'pint'), ('QUART', 'quart'), ('GALLON', 'gallon'), ('IMPERIAL_FLUID_OUNCE', 'imperial fluid ounce'), ('IMPERIAL_PINT', 'imperial pint'), ('IMPERIAL_QUART', 'imperial quart'), ('IMPERIAL_GALLON', 'imperial gallon')], max_length=128)),
                ('type', models.CharField(choices=[('WEIGHT', 'weight'), ('VOLUME', 'volume'), ('OTHER', 'other')], max_length=128)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataStoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.BigIntegerField(db_index=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_plugin.opendatacategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_plugin.opendatastore')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='opendatastore',
            name='categories',
            field=models.ManyToManyField(through='open_data_plugin.OpenDataStoreCategory', to='open_data_plugin.opendatacategory'),
        ),
        migrations.AddField(
            model_name='opendatastore',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OpenDataProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataFoodProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_amount', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_plugin.opendataproperty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('plural_name', models.CharField(max_length=128, unique=True)),
                ('fdc_id', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('preferred_shopping_unit_imperial', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_shopping_unit_imperial', to='open_data_plugin.opendataunit')),
                ('preferred_shopping_unit_metric', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_shopping_unit_metric', to='open_data_plugin.opendataunit')),
                ('preferred_unit_imperial', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_unit_imperial', to='open_data_plugin.opendataunit')),
                ('preferred_unit_metric', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_unit_metric', to='open_data_plugin.opendataunit')),
                ('properties', models.ManyToManyField(blank=True, to='open_data_plugin.opendatafoodproperty')),
                ('store_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_plugin.opendatacategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_amount', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('converted_amount', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('source', models.TextField()),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_base_relation', to='open_data_plugin.opendataunit')),
                ('converted_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_converted_relation', to='open_data_plugin.opendataunit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_plugin.opendatafood')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
