# Generated by Django 4.1.9 on 2023-05-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('open_data_plugin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opendatafoodproperty',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='opendatafoodproperty',
            name='slug',
        ),
        migrations.AlterField(
            model_name='opendatastorecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_to_store', to='open_data_plugin.opendatacategory'),
        ),
        migrations.AlterField(
            model_name='opendatastorecategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_to_store', to='open_data_plugin.opendatastore'),
        ),
    ]
