# Generated by Django 4.1.9 on 2023-05-22 15:21

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):
    dependencies = [
        ('open_data_plugin', '0002_remove_opendatafoodproperty_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendatafood',
            name='properties_food_amount',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='opendatafood',
            name='properties_food_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_plugin.opendataunit'),
        ),
        migrations.AddField(
            model_name='opendatafood',
            name='properties_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opendataproperty',
            name='fdc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
