# Generated by Django 4.1.9 on 2023-05-23 11:59

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('open_data_plugin', '0003_opendatafood_properties_food_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDataUser',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('moderator_user', models.BooleanField()),
                ('verified_user', models.BooleanField()),
            ],
        ),
    ]
