# Generated by Django 4.1.9 on 2023-06-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_plugin', '0006_opendataversion_opendatacategory_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendatacategory',
            name='description',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
