# Generated by Django 4.1.9 on 2023-06-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_plugin', '0007_opendatacategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendatacategory',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
