# Generated by Django 4.2.7 on 2024-01-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_plugin', '0008_alter_opendatacategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendatafood',
            name='fdc_id',
            field=models.CharField(max_length=128),
        ),
    ]
