# Generated by Django 4.2.7 on 2024-02-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_plugin', '0009_alter_opendatafood_fdc_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='opendataconversion',
            constraint=models.UniqueConstraint(fields=('base_unit', 'converted_unit', 'food'), name='f_unique_conversion_per_food'),
        ),
    ]
