# Generated by Django 4.2.22 on 2025-07-18 11:18

from django.db import migrations, models

def change_base_unit_case(apps, schema_editor):
    """
    In this migration, a unique constraint is set on the fields `recipe` and `book`.
    If there are already duplicate entries, the migration will fail.
    Therefore all duplicate entries are deleted beforehand.
    """
    OpenDataUnit = apps.get_model('open_data_plugin', 'OpenDataUnit')

    OpenDataUnit.objects.filter(base_unit='G').update(base_unit='g')
    OpenDataUnit.objects.filter(base_unit='KG').update(base_unit='kg')
    OpenDataUnit.objects.filter(base_unit='OUNCE').update(base_unit='ounce')
    OpenDataUnit.objects.filter(base_unit='POUND').update(base_unit='pound')
    OpenDataUnit.objects.filter(base_unit='ML').update(base_unit='ml')
    OpenDataUnit.objects.filter(base_unit='L').update(base_unit='l')
    OpenDataUnit.objects.filter(base_unit='FLUID_OUNCE').update(base_unit='fluid_ounce')
    OpenDataUnit.objects.filter(base_unit='QUART').update(base_unit='quart')
    OpenDataUnit.objects.filter(base_unit='GALLON').update(base_unit='gallon')
    OpenDataUnit.objects.filter(base_unit='TBSP').update(base_unit='tbsp')
    OpenDataUnit.objects.filter(base_unit='TSP').update(base_unit='tsp')
    OpenDataUnit.objects.filter(base_unit='CUP').update(base_unit='us_cup')
    OpenDataUnit.objects.filter(base_unit='IMPERIAL_FLUID_OUNCE').update(base_unit='imperial_fluid_ounce')
    OpenDataUnit.objects.filter(base_unit='IMPERIAL_PINT').update(base_unit='imperial_pint')
    OpenDataUnit.objects.filter(base_unit='IMPERIAL_QUART').update(base_unit='imperial_quart')
    OpenDataUnit.objects.filter(base_unit='IMPERIAL_GALLON').update(base_unit='imperial_gallon')

class Migration(migrations.Migration):

    dependencies = [
        ('open_data_plugin', '0010_opendataconversion_f_unique_conversion_per_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendataunit',
            name='base_unit',
            field=models.CharField(blank=True, choices=[('G', 'g'), ('KG', 'kg'), ('OUNCE', 'ounce'), ('POUND', 'pound'), ('ML', 'ml'), ('L', 'l'), ('FLUID_OUNCE', 'fluid_ounce'),
                                                        ('PINT', 'pint'), ('QUART', 'quart'), ('GALLON', 'gallon'), ('TBSP', 'tbsp'), ('TSP', 'tsp'), ('CUP', 'cup'),
                                                        ('IMPERIAL_FLUID_OUNCE', 'imperial fluid ounce'), ('IMPERIAL_PINT', 'imperial pint'), ('IMPERIAL_QUART', 'imperial quart'),
                                                        ('IMPERIAL_GALLON', 'imperial gallon'), ('g', 'g'), ('kg', 'kg'), ('ounce', 'ounce'), ('pound', 'pound'), ('ml', 'ml'), ('l', 'l'),
                                                        ('fluid_ounce', 'fluid_ounce'), ('pint', 'pint'), ('quart', 'quart'), ('gallon', 'gallon'), ('tbsp', 'tbsp'), ('tsp', 'tsp'),
                                                        ('us_cup', 'US Cup'), ('imperial_fluid_ounce', 'imperial fluid ounce'), ('imperial_pint', 'imperial pint'), ('imperial_quart', 'imperial quart'),
                                                        ('imperial_gallon', 'imperial gallon'), ('imperial_tbsp', 'imperial tbsp'), ('imperial_tsp', 'imperial tsp')], max_length=128),
        ),
        migrations.RunPython(change_base_unit_case),
        migrations.AlterField(
            model_name='opendataunit',
            name='base_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ounce', 'ounce'), ('pound', 'pound'), ('ml', 'ml'),
                                                        ('l', 'l'), ('fluid_ounce', 'fluid_ounce'), ('pint', 'pint'), ('quart', 'quart'), ('gallon', 'gallon'), ('tbsp', 'tbsp'),
                                                        ('tsp', 'tsp'), ('us_cup', 'US Cup'), ('imperial_fluid_ounce', 'imperial fluid ounce'), ('imperial_pint', 'imperial pint'),
                                                        ('imperial_quart', 'imperial quart'), ('imperial_gallon', 'imperial gallon'), ('imperial_tbsp', 'imperial tbsp'),
                                                        ('imperial_tsp', 'imperial tsp')], max_length=128),
        ),
    ]
