# Generated by Django 4.2.22 on 2025-07-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_plugin', '0011_alter_opendataunit_base_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendatafood',
            name='fdc_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
